name: turbo-ignore
description: Checks if a given package is affected by changes
author: valpinkman
inputs:
  head-ref:
    description: "name of branch or ref to compare with (defaults to 'develop')"
    default: develop
    required: false
  package:
    description: "name of the package to check for (package.json 'name' key)"
    required: true
  command:
    description: "turbo command to run (defaults to 'build')"
    default: build
    required: false
outputs:
  affected:
    description: "Returns 'true' if the package is affected by changes"

runs:
  using: node16
  main: build/main.js

branding:
  icon: shuffle
  color: green
