
name: CI
on:
  pull_request:
    branches: [ "release" ]
    
    #TODO check paths desktop & mobile
    paths: 
      - apps/ledger-live-desktop/static/i18n/**
      - apps/ledger-live-mobile/src/locales/**
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        prNumber: 
          description: Number of the PR
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release-translation-check:
    name: release branch translation check
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

#time to slack this bad boi

  report-on-slack:
      runs-on: ubuntu-latest
      steps:
      
      - name: format message
        uses: actions/github-script@v6
        id: message
        with:
            script: |
              const fs = require("fs");
              onst output = "";
              
              with:
               cond: ${{ github.event.event_name==" pull_request" }}
                if_true: 
                  output = {
                   "Translations files have changed on PR ${{ github.event.pull_request.number }}"
                   "- ${{ github.event.pull_request.title }}"
                   "- ${{ github.event.head_commit.message }}"
                  };
                if_false: 
                  output = {
                   "[Manual trigger for test] Translations files have changed on PR ${{ prNumber }}"
                  };

              fs.writeFileSync(`./payload-slack-content.json`, JSON.stringify(output, null, 2));
      - name: post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
              channel-id: "C040D9JMVQ8"
              payload-file-path: "./payload-slack-content.json"
        env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
